### ISSUE TITLE
How does the Docker image introduce the Macos SDK? Is the xcode protocol violated?

### ISSUE THREAD

**Issue by cmlmakahts** [shepherdjerred/macos-cross-compiler#1]
Section 2.5 in the xcode protocol indicates that the macos SDK cannot be used on non-Apple devices.
Does the introduction of the macos SDK into the docker image violate the xcode protocol?
https://www.apple.com/legal/sla/docs/xcode.pdf

**Comment by shepherdjerred** [comment]
Hi! I am not a lawyer; if you have a legal question you should consult with one.

I haven't received any communication from Apple that they consider this or similar projects as a violation of the linked document.
